export default function handler(req, res) {
  res.status(200).json({
    purecss: [
      {
        title: "Summer Girl",
        image: "summer-girl_DHnQLa-Fm.png",
        youtube: "https://youtu.be/1ojBO-FNYuI",
        codepen: "https://codepen.io/AsyrafHussin/pen/dymWPWo",
        github: "https://github.com/purecss-co/summer-girl",
        website: "",
        design: "https://dribbble.com/shots/6750609-Summer-Chic",
      },
      {
        title: "Captain Jack Sparrow",
        image: "jack-sparrow_cREUbgQ6M.png",
        youtube: "https://youtu.be/xq0J3e7wCi8",
        codepen: "https://codepen.io/AsyrafHussin/pen/abYmoMM",
        github: "https://github.com/purecss-co/jack-sparrow",
        website: "",
        design:
          "https://www.etsy.com/listing/1221585863/johnny-depp-svg-captain-pirate-svg",
      },
      {
        title: "Girl With Sunglasses",
        image: "girl-sunglasses_IwhLdZR1j.png",
        youtube: "https://youtu.be/onkqGNOrmQw",
        codepen: "https://codepen.io/AsyrafHussin/pen/OJvMRvN",
        github: "https://github.com/purecss-co/girl-sunglasses",
        website: "",
        design:
          "https://www.vectorstock.com/royalty-free-vector/fashion-portrait-of-a-model-girl-with-sunglasses-vector-22319637",
      },
      {
        title: "Woman Wearing Face Mask",
        image: "woman-face-mask_tjxnLZMhL.png",
        youtube: "https://youtu.be/Mbu2kkVTw8o",
        codepen: "https://codepen.io/AsyrafHussin/pen/LYdPOoG",
        github: "https://github.com/purecss-co/woman-face-mask",
        website: "",
        design:
          "https://www.vecteezy.com/vector-art/938443-woman-wearing-disposable-medical-face-mask",
      },
      {
        title: "The Lips",
        image: "the-lips_bz1PQ3v0O.png",
        youtube: "https://youtu.be/EblG8uz08qs",
        codepen: "https://codepen.io/AsyrafHussin/pen/JjpVMWB",
        github: "https://github.com/purecss-co/the-lips",
        website: "",
        design: "https://www.malikafavre.com/nyt",
      },
      {
        title: "The Professor",
        image: "professor_B0BxnuDm7.png",
        youtube: "https://youtu.be/ww1h0EMv-U0",
        codepen: "https://codepen.io/AsyrafHussin/pen/VwQqJRJ",
        github: "https://github.com/purecss-co/the-professor",
        website: "",
        design:
          "https://society6.com/product/la-casa-de-papel-tee-sirt-el-profesor_framed-print",
      },
      {
        title: "Johnny Depp",
        image: "johnny-depp_8suWePB3c.png",
        youtube: "https://youtu.be/wLPPIamk6cY",
        codepen: "https://codepen.io/AsyrafHussin/pen/MWQPOJG",
        github: "https://github.com/purecss-co/johnny-depp",
        website: "",
        design:
          "https://ditalgo.com/product/johnny-depp-svg-png-pdf-johnny-depp-silhouette/",
      },
      {
        title: "Marie",
        image: "marie__5hZQeskT.png",
        youtube: "https://youtu.be/EtX6W-UN5-M",
        codepen: "https://codepen.io/AsyrafHussin/pen/mdXjjzq",
        github: "https://github.com/purecss-co/marie",
        website: "",
        design: "https://shop.malikafavre.com/products/marie",
      },
      {
        title: "Cristiano Ronaldo",
        image: "ronaldo_4696Py_dS.png",
        youtube: "https://youtu.be/O_nE4O5JRBQ",
        codepen: "https://codepen.io/AsyrafHussin/pen/rNJvMrv",
        github: "https://github.com/purecss-co/ronaldo",
        website: "",
        design: "https://dribbble.com/shots/6564093-Ronaldo",
      },
      {
        title: "The Looked",
        image: "the-looked_hHTvghW71.png",
        youtube: "https://youtu.be/ZkeCBhwoS3Q",
        codepen: "https://codepen.io/AsyrafHussin/pen/wvyyNjY",
        github: "https://github.com/purecss-co/the-looked",
        website: "",
        design: "https://www.behance.net/gallery/45318637/Women-Uncovered",
      },
      {
        title: "Red Hat Lady",
        image: "redhatlady_5j86mlErj.png",
        youtube: "https://youtu.be/ZEaSiyVGFDg",
        codepen: "https://codepen.io/AsyrafHussin/pen/PoQEjvz",
        github: "https://github.com/purecss-co/red-hat-lady",
        website: "",
        design: "https://www.behance.net/gallery/40978369/illustration",
      },
      {
        title: "Fashion Woman",
        image: "fashion-woman_LY-mlLpb1.png",
        youtube: "https://youtu.be/l6BebWGajcY",
        codepen: "https://codepen.io/AsyrafHussin/pen/jOZaNVE",
        github: "https://github.com/purecss-co/fashion-woman",
        website: "",
        design:
          "https://www.behance.net/gallery/113097137/Fashion-woman-in-style-Pop-art",
      },
      {
        title: "The Queen's Gambit",
        image: "queensgambit_YcQ_LxMeU.png",
        youtube: "https://youtu.be/cqfB2t0ZvNc",
        codepen: "https://codepen.io/AsyrafHussin/pen/YzeZKJZ",
        github: "https://github.com/purecss-co/the-queens-gambit",
        website: "",
        design: "https://dribbble.com/shots/14575504-Queens-Gambit",
      },
      {
        title: "BNB Chain Logo",
        image: "bnbchain_72-9hMpcs.png",
        youtube: "https://youtu.be/o7RTE5OAfnU",
        codepen: "https://codepen.io/AsyrafHussin/pen/ZEvPdPg",
        github: "https://github.com/purecss-co/bnb-chain-logo",
        website: "https://www.bnbchain.world/",
        design: "",
      },
      {
        title: "Adobe Logo",
        image: "adobe_fx5kFX2r7.png",
        youtube: "https://youtu.be/rgznPBO8Nno",
        codepen: "https://codepen.io/AsyrafHussin/pen/ZEypoZY",
        github: "https://github.com/purecss-co/adobe-logo",
        website: "https://www.adobe.com/",
        design: "",
      },
      {
        title: "Tailwind CSS Logo",
        image: "tailwindcss_kei78MCNj.png",
        youtube: "https://youtu.be/A7C7wmER0zw",
        codepen: "https://codepen.io/AsyrafHussin/pen/gORadZO",
        github: "https://github.com/purecss-co/tailwindcss-logo",
        website: "https://tailwindcss.com/",
        design: "",
      },
      {
        title: "PancakeSwap Logo",
        image: "pancakeswap_8vFXOab2Z.png",
        youtube: "https://youtu.be/sPEvUxQKdkQ",
        codepen: "https://codepen.io/AsyrafHussin/pen/wvdZwrJ",
        github: "https://github.com/purecss-co/pancakeswap-logo",
        website: "https://pancakeswap.finance",
        design: "",
      },
      {
        title: "Charlie Chaplin",
        image: "charlie-chaplin_kgZaWBL2Z.png",
        youtube: "https://youtu.be/iwu-eNvkbS8",
        codepen: "https://codepen.io/AsyrafHussin/pen/mdOdyKo",
        github: "https://github.com/purecss-co/charlie-chaplin",
        website: "",
        design: "",
      },
      {
        title: "Elon Musk",
        image: "elon-musk_MWGhCn-fI.png",
        youtube: "https://youtu.be/6_4Xvu5uVWM",
        codepen: "https://codepen.io/AsyrafHussin/pen/mdroBzv",
        github: "https://github.com/purecss-co/elon-musk",
        website: "",
        design: "",
      },
      {
        title: "Lynn Fisher Avatar",
        image: "lynnfisher_xUPIde_vw.png",
        youtube: "https://youtu.be/ipSuVy7-HXk",
        codepen: "https://codepen.io/AsyrafHussin/pen/VwKBQVb",
        github: "https://github.com/purecss-co/lynn-fisher-avatar",
        website: "https://lynnandtonic.com/",
        design: "",
      },
      {
        title: "2021",
        image: "2021_GnTL5qw68.png",
        youtube: "https://youtu.be/UW1bAof7SmU",
        codepen: "https://codepen.io/AsyrafHussin/pen/GRjQzMz",
        github: "https://github.com/purecss-co/2021",
        website: "",
        design: "https://dribbble.com/shots/14829754-2021",
      },
      {
        title: "Ruby on Rails Logo",
        image: "rails_0MpK0NpAK.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/jOMEqMR",
        github: "https://github.com/purecss-co/rails-logo",
        website: "https://rubyonrails.org/",
        design: "",
      },
      {
        title: "PHP 8 Logo",
        image: "php-8_nBvjilbLi.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/GRjRdqr",
        github: "https://github.com/purecss-co/php-8-logo",
        website: "https://www.php.net/releases/8.0/en.php",
        design: "",
      },
      {
        title: "Laravel Logo",
        image: "laravel_mCWkyXNcP.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MWeNjJg",
        github: "https://github.com/purecss-co/laravel-logo",
        website: "https://laravel.com/",
        design: "",
      },
      {
        title: "The Queen's Gambit",
        image: "queens-gambit_zNJBr1CIm.png",
        youtube: "https://youtu.be/4nlMUYC3Qi8",
        codepen: "https://codepen.io/AsyrafHussin/pen/wvWLRpO",
        github: "https://github.com/purecss-co/queens-gambit",
        website: "",
        design: "https://dribbble.com/shots/14571164-Queen-s-Gambit",
      },
      {
        title: "Chicken",
        image: "chicken_OGApUYm1e.png",
        youtube: "https://youtu.be/0NM1yWQhsuI",
        codepen: "https://codepen.io/AsyrafHussin/pen/QWEXgrZ",
        github: "https://github.com/purecss-co/chicken",
        website: "",
        design: "https://dribbble.com/shots/5259998-Chicken",
      },
      {
        title: "PS5 Logo",
        image: "ps5_W6zJRlidM.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/ZEONdwE",
        github: "https://github.com/purecss-co/ps5-logo",
        website: "",
        design: "",
      },
      {
        title: "DigitalOcean Sammy the Shark",
        image: "sammy-the-shark_2DdH6__PQ.png",
        youtube: "https://youtu.be/6UsmWZqpfE8",
        codepen: "https://codepen.io/AsyrafHussin/pen/gOMJPxy",
        github: "https://github.com/purecss-co/sammy-the-shark",
        website: "https://www.digitalocean.com/",
        design: "",
      },
      {
        title: "JomLaunch Logo",
        image: "jomlaunch_WlH8jlitK.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rNLbvZp",
        github: "https://github.com/purecss-co/jomlaunch-logo",
        website: "https://launch.jomweb.my/",
        design: "",
      },
      {
        title: "Sports Car",
        image: "sports-car_YGQE9M4lh.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/ZEQXXrx",
        github: "https://github.com/purecss-co/sports-car",
        website: "",
        design: "https://dribbble.com/shots/3252634-Sports-Car",
      },
      {
        title: "Chris Coyier Pixel Avatar",
        image: "chris-coyier_VxN9VR3tL.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/RwraJRm",
        github: "https://github.com/purecss-co/chris-coyier-pixel-avatar",
        website: "",
        design: "",
      },
      {
        title: "Tesla Logo",
        image: "tesla_H3Aaq2GDs.png",
        youtube: "https://youtu.be/J0HttRbh0Ic",
        codepen: "https://codepen.io/AsyrafHussin/pen/MWKaQBZ",
        github: "https://github.com/purecss-co/tesla-logo",
        website: "https://www.tesla.com",
        design: "",
      },
      {
        title: "SpaceX Logo",
        image: "spacex_yRYrr8IGb.png",
        youtube: "https://youtu.be/6IoveDpEkiY",
        codepen: "https://codepen.io/AsyrafHussin/pen/yLeYPyr",
        github: "https://github.com/purecss-co/spacex-logo",
        website: "https://www.spacex.com",
        design: "",
      },
      {
        title: "My Pixel Avatar",
        image: "pixel-avatar_ClOa3Jp7i.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/qBbBXxB",
        github: "https://github.com/purecss-co/my-pixel-avatar",
        website: "",
        design: "",
      },
      {
        title: "3D Ball",
        image: "3d-ball_XB0pfxyom.png",
        youtube: "https://youtu.be/2qjQV_rsAV8",
        codepen: "https://codepen.io/AsyrafHussin/pen/dyYeBgv",
        github: "https://github.com/purecss-co/3d-ball",
        website: "",
        design: "",
      },
      {
        title: "Bear",
        image: "bear_KlWjteknp.png",
        youtube: "https://youtu.be/TqVh_3zke-o",
        codepen: "https://codepen.io/AsyrafHussin/pen/rNOdRXM",
        github: "https://github.com/purecss-co/bear",
        website: "",
        design: "https://dribbble.com/shots/11321693-Bear",
      },
      {
        title: "Hijab Girl Portrait",
        image: "hijab-girl_ku9xtq28m.png",
        youtube: "https://youtu.be/1w50XwL6W7E",
        codepen: "https://codepen.io/AsyrafHussin/pen/bGVYOjY",
        github: "https://github.com/purecss-co/hijab-girl",
        website: "",
        design: "https://dribbble.com/shots/5950905-Veil-Logo",
      },
      {
        title: "Lady in Blue Portrait",
        image: "lady-in-blue_DxDzpVCIh.png",
        youtube: "https://youtu.be/OEX5MaJmTrY",
        codepen: "https://codepen.io/AsyrafHussin/pen/zYvwemL",
        github: "https://github.com/purecss-co/lady-in-blue",
        website: "",
        design: "https://dribbble.com/shots/11135126-Lady-In-Blue/",
      },
      {
        title: "Mo Salah Poster",
        image: "mosalah_VIyE54y4j.png",
        youtube: "https://youtu.be/nCLBa4hpFN8",
        codepen: "https://codepen.io/AsyrafHussin/pen/QWjLqqx",
        github: "https://github.com/purecss-co/mo-salah-poster",
        website: "",
        design: "https://www.uplabs.com/posts/mohamed-salah-poster",
      },
      {
        title: "Dwayne Johnson (The Rock) Portrait",
        image: "the-rock_czPaGPYbj.png",
        youtube: "https://youtu.be/SG5l6MJsgNo",
        codepen: "https://codepen.io/AsyrafHussin/pen/WqQPRm",
        github: "https://github.com/purecss-co/purecss-dwayne-johnson",
        website: "",
        design: "",
      },
      {
        title: "Keanu Reeves (John Wick) Portrait",
        image: "john-wick_C4prC2FUb.png",
        youtube: "https://youtu.be/dJhcorlzOcY",
        codepen: "https://codepen.io/AsyrafHussin/pen/qzBLVj",
        github: "https://github.com/purecss-co/purecss-keanu-reeves",
        website: "",
        design: "",
      },
      {
        title: "Gatsby Logo",
        image: "gatsby_FCGbDuS-p.png",
        youtube: "https://youtu.be/8gvxztLqEt4",
        codepen: "https://codepen.io/AsyrafHussin/pen/KLOwdz",
        github: "https://github.com/purecss-co/purecss-gatsby-logo",
        website: "https://www.gatsbyjs.org",
        design: "",
      },
      {
        title: "Sandwich",
        image: "sandwich_xsNaX2KAE.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/byPLQK",
        github: "https://github.com/purecss-co/purecss-sandwich",
        website: "",
        design: "https://dribbble.com/shots/5312830-Sandwich",
      },
      {
        title: "Letter M",
        image: "letter-m_hwWbxrZYu.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/OYqjRm",
        github: "https://github.com/purecss-co/purecss-letter-m",
        website: "",
        design: "https://dribbble.com/shots/6315007-M-Logo",
      },
      {
        title: "Letter T",
        image: "letter-t_G8hru4-asd.png",
        youtube: "https://youtu.be/6I6ovliHhnk",
        codepen: "https://codepen.io/AsyrafHussin/pen/yWGwGx",
        github: "https://github.com/purecss-co/purecss-letter-t",
        website: "",
        design: "https://dribbble.com/shots/6176376-T-Letter-Logo",
      },
      {
        title: "Space Helemt",
        image: "space-helmet_jUuZQhIPS.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/EzGmGR",
        github: "https://github.com/purecss-co/purecss-space-helmet",
        website: "",
        design: "https://www.uplabs.com/posts/astrounut-space-helmet",
      },
      {
        title: "Netlify Logo",
        image: "netlify_1pO-QNpVv.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/PvyORQ",
        github: "https://github.com/purecss-co/purecss-netlify-logo",
        website: "https://www.netlify.com",
        design: "",
      },
      {
        title: "Unicorn Logo",
        image: "unicorn-logo_sH5B-kBoP.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MdBeYg",
        github: "https://github.com/purecss-co/purecss-unicorn-logo",
        website: "",
        design: "https://dribbble.com/shots/5774723-Unicorn-logo",
      },
      {
        title: "Chrome V8 Logo",
        image: "v8_4fryqfKCv.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/KLRZqQ",
        github: "https://github.com/purecss-co/purecss-chrome-v8-logo",
        website: "https://v8.dev",
        design: "",
      },
      {
        title: "Bob The Minion",
        image: "minion_SC8IERrFM.png",
        youtube: "https://youtu.be/xTlgtPEOQd0",
        codepen: "https://codepen.io/AsyrafHussin/pen/wXjpyB",
        github: "https://github.com/purecss-co/purecss-bob-minion",
        website: "",
        design: "https://www.uplabs.com/posts/bob-minion",
      },
      {
        title: "Sketch Logo",
        image: "sketch_U_M6t6QsA.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/OEvEBz",
        github: "https://github.com/purecss-co/purecss-sketch-logo",
        website: "https://www.sketchapp.com",
        design: "",
      },
      {
        title: "Work Desk",
        image: "workdesk_5DvJo_0N6.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/GGQaGM",
        github: "https://github.com/purecss-co/purecss-work-desk",
        website: "",
        design: "https://www.uplabs.com/posts/work_desk",
      },
      {
        title: "Discord Logo",
        image: "discord_NmEu8xcxh.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/VdyqOa",
        github: "https://github.com/purecss-co/purecss-discord-logo",
        website: "https://discordapp.com",
        design: "",
      },
      {
        title: "Angular Logo",
        image: "angular_wgkGLYsyG.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/zappyQ",
        github: "https://github.com/purecss-co/purecss-angular-logo",
        website: "https://angular.io",
        design: "",
      },
      {
        title: "Reddit Loader",
        image: "reddit-loader_X2oaxsr3V.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/OEOZVW",
        github: "https://github.com/purecss-co/purecss-reddit-loader",
        website: "https://www.reddit.com",
        design: "",
      },
      {
        title: "Reddit Logo",
        image: "reddit_EI5HYj7i8.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/bKYvpd",
        github: "https://github.com/purecss-co/purecss-reddit-logo",
        website: "https://www.reddit.com",
        design: "",
      },
      {
        title: "Unicorn",
        image: "unicorn_ONHDcY7HC.png",
        youtube: "https://youtu.be/xYmAUjP2Keo",
        codepen: "https://codepen.io/AsyrafHussin/pen/YvEpWE",
        github: "https://github.com/purecss-co/purecss-unicorn",
        website: "",
        design: "https://dribbble.com/shots/1466843-Unicorn",
      },
      {
        title: "Wahdah Logo",
        image: "wahdah_U6hJakCkv.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/bKrbRd",
        github: "https://github.com/purecss-co/purecss-wahdah-logo",
        website: "https://www.wahdah.my",
        design: "",
      },
      {
        title: "DigitalOcean Logo",
        image: "digitalocean_kCfSoz0hz.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/YvVKaX",
        github: "https://github.com/purecss-co/purecss-digitalocean-logo",
        website: "https://www.digitalocean.com",
        design: "",
      },
      {
        title: "WordPress Logo",
        image: "wordpress_oDQkBgo6e.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MXJqWb",
        github: "https://github.com/purecss-co/purecss-wordpress-logo",
        website: "https://wordpress.com",
        design: "",
      },
      {
        title: "Iron Man 2 Arc Reactor",
        image: "arc-reactor-2_Yq9TAKOE0.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/XYpjjV",
        github: "https://github.com/purecss-co/purecss-ironman2-arcreactor",
        website: "",
        design: "",
      },
      {
        title: "Git Logo",
        image: "git_HYPGCBWmg.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/ERyQGm",
        github: "https://github.com/purecss-co/purecss-git-logo",
        website: "https://git-scm.com",
        design: "",
      },
      {
        title: "GitLab Logo",
        image: "gitlab_Ff-QVlWjj.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/VdaxqW",
        github: "https://github.com/purecss-co/purecss-gitlab-logo",
        website: "https://gitlab.com",
        design: "",
      },
      {
        title: "Avengers Logo",
        image: "avengers_0-QZdm1H5.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/RJrywp",
        github: "https://github.com/purecss-co/purecss-avengers-logo",
        website: "http://marvel.com/avengers",
        design: "",
      },
      {
        title: "Ubuntu Logo",
        image: "ubuntu_LFtrW7kP5.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/PaPMYE",
        github: "https://github.com/purecss-co/purecss-ubuntu-logo",
        website: "https://www.ubuntu.com",
        design: "",
      },
      {
        title: "Katsana Sticker",
        image: "katsana_kFZYTW9eT.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/NzqJWa",
        github: "https://github.com/purecss-co/purecss-katsana-sticker",
        website: "https://www.katsana.com",
        design: "",
      },
      {
        title: "Laman7 Logo",
        image: "laman7_zLPa7apxx.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/wXBVzb",
        github: "https://github.com/purecss-co/purecss-laman7-logo",
        website: "https://laman7.com",
        design: "",
      },
      {
        title: "Shazam Listening Song",
        image: "shazam_7sjDRBatoT.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/zaxGeg",
        github: "https://github.com/purecss-co/purecss-shazam-logo",
        website: "https://www.shazam.com",
        design: "",
      },
      {
        title: "OMG Hackers Logo",
        image: "omgh_jdu4bS-Vj.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/PaYjbX",
        github: "https://github.com/purecss-co/purecss-omgh-logo",
        website: "https://omghackers.com",
        design: "",
      },
      {
        title: "Amanz Logo",
        image: "amanz_vUNM3nRRz.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/yjWKWE",
        github: "https://github.com/purecss-co/purecss-amanz-logo",
        website: "https://amanz.my",
        design: "",
      },
      {
        title: "JomParking Logo",
        image: "jomparking_cim5K2Tzp.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rKNBdE",
        github: "https://github.com/purecss-co/purecss-jomparking-logo",
        website: "https://www.jomparking.com",
        design: "",
      },
      {
        title: "SumberManusia Old Logo",
        image: "sm_RtGVcW3y9.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/KRLyrZ",
        github: "https://github.com/purecss-co/purecss-sumbermanusia-logo",
        website: "https://sumbermanusia.my",
        design: "",
      },
      {
        title: "Iron Man Arc Reactor",
        image: "arc-reactor_kRQEt4SxN.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/odVpmE",
        github: "https://github.com/purecss-co/purecss-ironman-arcreactor",
        website: "",
        design: "",
      },
      {
        title: "eSentral Logo",
        image: "esentral_Tz5mzue6S.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/odVGKr",
        github: "https://github.com/purecss-co/purecss-esentral",
        website: "https://www.e-sentral.com",
        design: "",
      },
      {
        title: "ReactJS Logo",
        image: "reactjs_fanWT6r7v.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/vjbOdE",
        github: "https://github.com/purecss-co/purecss-reactjs-logo",
        website: "https://reactjs.org",
        design: "",
      },
      {
        title: "Firebase Logo",
        image: "firebase_KVht9td2K.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/NMoPLq",
        github: "https://github.com/purecss-co/purecss-firebase-logo",
        website: "https://firebase.google.com",
        design: "",
      },
      {
        title: "Deadpool Logo",
        image: "deadpool_KIytgHQJG.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/aGPKPg",
        github: "https://github.com/purecss-co/purecss-deadpool-logo",
        website: "",
        design: "",
      },
      {
        title: "The Flash Logo",
        image: "theflash_9gWCpwqNd.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/JveQYX",
        github: "https://github.com/purecss-co/purecss-theflash-logo",
        website: "",
        design: "",
      },
      {
        title: "TensorFlow Logo",
        image: "tensorflow_sa1lkdTpE.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/qVBrrv",
        github: "https://github.com/purecss-co/purecss-tensorflow-logo",
        website: "https://www.tensorflow.org",
        design: "",
      },
      {
        title: "Runcloud Logo",
        image: "runcloud_r5lyA9plZ.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/aVoaYr",
        github: "https://github.com/purecss-co/purecss-runcloud-logo",
        website: "https://runcloud.io",
        design: "",
      },
      {
        title: "iPhone 8 White Edition",
        image: "iphone8_03gP6s2BF.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/BwgBLe",
        github: "https://github.com/purecss-co/purecss-iphone-8",
        website: "",
        design: "",
      },
      {
        title: "Pixel 2 XL White Edition",
        image: "pixel_PUC5mNAHi.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rGRXKy",
        github: "https://github.com/purecss-co/purecss-pixel2xl",
        website: "",
        design: "",
      },
      {
        title: "Galaxy S8 Coral Blue Edition",
        image: "galaxys8_ogAz6AcdA.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MELpGo",
        github: "https://github.com/purecss-co/purecss-galaxy-s8",
        website: "",
        design: "",
      },
      {
        title: "iPhone X White Edition",
        image: "iphoneX_P-llzBElj.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/mBaBXm",
        github: "https://github.com/purecss-co/purecss-iphone-x",
        website: "",
        design: "",
      },
    ],
  });
}
